POST http://localhost:3000/api/get_article_list_and_view
content-type: application/json

{
    "user_id": 1,
    "start_index": "1",
    "number_of_article": "5"
}
####

return
[
    {
        "article_id": 1,
        "article_title": "A history of fashion",
        "author_name": "Violet Lee",
        "author_pfp": "www.violetleepfp.com",
        "date_posted": "12/25/2021 15:19:00",
        "total_invested": 432,
        "image_url": "http://backgroundImage",
        "tags": "for you, fashion"
    },
    {
        "article_id": 2,
        "article_title": "A history of fashion",
        "author_name": "Violet Lee",
        "author_pfp": "www.violetleepfp.com",
        "date_posted": "12/25/2021 15:19:00",
        "total_invested": 432,
        "image_url": "http://backgroundImage",
        "tags": "for you, fashion"
    },
    {
        "article_id": 3,
        "article_title": "A history of fashion",
        "author_name": "Violet Lee",
        "author_pfp": "www.violetleepfp.com",
        "date_posted": "12/25/2021 15:19:00",
        "total_invested": 432,
        "image_url": "http://backgroundImage",
        "tags": "for you, fashion"
    },
    {
        "article_id": 4,
        "article_title": "A history of fashion",
        "author_name": "Violet Lee",
        "author_pfp": "www.violetleepfp.com",
        "date_posted": "12/25/2021 15:19:00",
        "total_invested": 432,
        "image_url": "http://backgroundImage",
        "tags": "for you, fashion"
    },
    {
        "article_id": 5,
        "article_title": "A history of fashion",
        "author_name": "Violet Lee",
        "author_pfp": "www.violetleepfp.com",
        "date_posted": "12/25/2021 15:19:00",
        "total_invested": 432,
        "image_url": "http://backgroundImage",
        "tags": "for you, fashion"
    }
]
###
POST http://localhost:3000/api/check_already_paid
content-type: application/json

{
    "user_id": 2,
    "article_id": 1
}
###
return
{
    "paid_or_not": true, //true = paid, false = haven't paid
    "paid": {
        "article_id": 1,
        "article_image_url": "http://backgroundImage",
        "article_title": "The History of Fashion",
        "article_author_name": "Violet Lee",
        "author_pfp": "http://authorpfp",
        "article_body": "Hi guys! I don’t know about you, but I am SO ready for spring! I’ve been posting some of my recent spring finds and what I’ve ordered and wanted to share last months most loved aka best-sellers!"
    }
}
###
POST http://localhost:3000/api/get_article_homepage
content-type: application/json

{
    "article_id": 1

}
###
return
{
    "image_url": "http://backgroundImage",
    "article_title": "A History of Fashion",
    "article_author": "Violet Lee",
    "author_pfp": "www.violetleepfp.com",
    "article_description": "fashion has always been my passion!",
    "article_price": 10,
    "article_liquidation_time": 4,
    "article_total_invested": 432
}
###
POST http://localhost:3000/api/pay_command
content-type: application/json

{
    "article_id": 1,
    "amount": 10,
    "transaction_type": 1 //1 = pay to read 2 = upvote 3 = cash out
}
###
return
{
    "err": //empty = success, not empty = error msg
}
###
POST http://localhost:3000/api/get_read_page
content-type: application/json

{
    "article_id": 1,
    "user_id": 2,
}
###
return
{
    "article_id": 1,
    "article_image_url": "http://backgroundImage",
    "article_title": "The History of Fashion",
    "article_author_name": "Violet Lee",
    "author_pfp": "http://authorpfp",
    "article_body": "Hi guys! I don’t know about you, but I am SO ready for spring! I’ve been posting some of my recent spring finds and what I’ve ordered and wanted to share last months most loved aka best-sellers!"
}
###
POST http://localhost:3000/api/get_statistics
content-type: application/json

{
    "article_id": 1,
    "user_id": 2
}
###
return
{
    "article_liquidation_time": 4,
    "article_total_invested": 439,
    "article_user_stake": 0.038724373,
    "article_user_investment": 17
}
###
POST http://localhost:3000/api/upvote_command
content-type: application/json

{
    "article_id": 1,
    "amount": 5,
    "user_id": 2
}
###
return
{
    "err": //empty = success, not empty = error msg
}
###
POST http://localhost:3000/api/is_balance_enough
content-type: application/json

{
    "amount": 5,
    "user_id": 2
}
###
return
{
    "is_balance_enough": true
}
###
POST http://localhost:3000/api/user_profile_page
content-type: application/json

{
    "user_id": 1
}
###
return
{
    "username": "Violet Lee",
    "#_followers": 354,
    "#_following": 345,
    "User_bio": "This is Violet",
    "user_pfp": "http://pfpImage",
    "wallet_balance": 3456
}
###

POST http://localhost:3000/api/investments_page
content-type: application/json

{
    "user_id": 2
}
###
return
{
    "article_id": 1,
    "article_title": "A History of Fashion",
    "author": "Violet Lee",
    "author_pic": "http://pfpImage",
    "image_url": "http://ImageURL",
    "total_TEA_invested": 444,
    "user_stake": 22,
    "liquidation_time": 4,
    "date_posted": "12/25/2021 15:19:00"
}
###
POST http://localhost:3000/api/cash_out_command
content-type: application/json

{
    "user_id": 2,
    "article_id": 1,
    "amount": 5
}
###
return
{
    "err": //empty = success, not empty = error msg
}
###
POST http://localhost:3000/api/article_prep_page
content-type: application/json

{
    "user_id": 3
}
###
return
{
    "err": //empty = success, not empty = error msg
}
###
POST http://localhost:3000/api/article_confirmation_page
content-type: application/json

{
    "article_id": 4
}
###
return
{
    "article_title": "Top Prom Dresses picks (WEE!)",
    "liquidation_time": 3,
    "total_TEA_invested": 34
}
###
GET http://192.168.1.15:3000/