POST http://localhost:3000/api/get_article_list_and_view
content-type: application/json

{
    "user_id": 1,
    "start_index": "1",
    "number_of_article": "5"
}
###
return
[
    {
        "article_id": 1,
        "article_title": "Why Python is The Future",
        "author_name": "Ephraim Jones",
        "author_pfp": "www.ejpfp.com",
        "date_posted": "1/03/2022 15:19:00",
        "total_invested": 10025,
        "image_url": "http://backgroundImage",
        "tags": "for you, coding"
    },
    {
        "article_id": 2,
        "article_title": "Super Chewy Cookies Recipe",
        "author_name": "Eliza Mae",
        "author_pfp": "www.empfp.com",
        "date_posted": "1/21/2022 15:19:00",
        "total_invested": 7342,
        "image_url": "http://backgroundImage",
        "tags": "for you, baking"
    },
    {
        "article_id": 3,
        "article_title": "The Go-To-Market Guide",
        "author_name": "Cecelia Hong",
        "author_pfp": "www.ch.com",
        "date_posted": "1/07/2022 15:19:00",
        "total_invested": 8961,
        "image_url": "http://backgroundImage",
        "tags": "for you, business"
    },
    {
        "article_id": 4,
        "article_title": "The Rules of Digital Marketing",
        "author_name": "Melissa Shen",
        "author_pfp": "www.mspfp.com",
        "date_posted": "12/25/2021 15:19:00",
        "total_invested": 9456,
        "image_url": "http://backgroundImage",
        "tags": "for you, marketing"
    },
    {
        "article_id": 5,
        "article_title": "Building muscle the right way",
        "author_name": "Darren Jones",
        "author_pfp": "www.djpfp.com",
        "date_posted": "1/24/2022 15:19:00",
        "total_invested": 11275,
        "image_url": "http://backgroundImage",
        "tags": "for you, fashion"
    }
]
###
POST http://localhost:3000/api/get_article_homepage
content-type: application/json

{
    "article_id": 2

}
###
return
{
    "image_url": "http://backgroundImage",
    "article_title": "Super Chewy Cookies Recipe",
    "article_author": "Eliza Mae",
    "author_pfp": "www.empfp.com",
    "article_description": "This recipe will teach you the most awesome way to make amazingly chewy cookie that will make your grandma proud.",
    "article_price": 20,
    "article_liquidation_time": 2,
    "article_total_invested": 100
}
###
POST http://localhost:3000/api/check_already_paid
content-type: application/json

{
    "user_id": 2,
    "article_id": 1
}
###:
return
{
    "paid_or_not": true, //true = paid, false = haven't paid
    "article_id": 1,
    "article_image_url": "http://backgroundImage",
    "article_title": "The History of Fashion",
    "article_author_name": "Violet Lee",
    "author_pfp": "http://authorpfp",
    "article_body": "Hi guys! I don’t know about you, but I am SO ready for spring! I’ve been posting some of my recent spring finds and what I’ve ordered and wanted to share last months most loved aka best-sellers!"
}
###
POST http://localhost:3000/api/pay_command
content-type: application/json

{
    "article_id": 1,
    "amount": 10,
    "transaction_type": 1 //1 = pay to read 2 = upvote 3 = cash out
}
###
return
{
    "err": //empty = success, not empty = error msg
}
###
POST http://localhost:3000/api/get_read_page
content-type: application/json

{
    "article_id": 2,
    "user_id": 2,
}
###
return
{
    "article_id": 2,
    "article_image_url": "http://backgroundImage",
    "article_title": "Super Chewy Cookies Recipe",
    "article_author_name": "Eliza Mae",
    "author_pfp": "http://empfp",
    "article_body": "Hiya there! If you asked me how many recipes I’ve tried to get super chewy, PERFECT cookies, I couldn’t even tell you. But what I can tell you, is the recipe that FINALLY worked for me."
}
###
POST http://localhost:3000/api/get_statistics
content-type: application/json

{
    "article_id": 2,
    "user_id": 2
}
###
return
{
    "article_liquidation_time": 2,
    "article_total_invested": 120,
    "article_user_stake": 0.1667,
    "article_user_investment": 20
}
###
POST http://localhost:3000/api/upvote_command
content-type: application/json

{
    "article_id": 2,
    "amount": 10,
    "user_id": 2
}
###
return
{
    "err": //empty = success, not empty = error msg
}
###
POST http://localhost:3000/api/is_balance_enough
content-type: application/json

{
    "amount": 10,
    "user_id": 2
}
###
return
{
    "is_balance_enough": true
}
###
POST http://localhost:3000/api/user_profile_page
content-type: application/json

{
    "user_id": 2
}
###
return
{
    "username": "Jessica Covington",
    "#_followers": 0,
    "#_following": 0,
    "User_bio": "Your bio is empty",
    "user_pfp": "http://pfpImage",
    "wallet_balance": 1326
}
###

POST http://localhost:3000/api/investments_page
content-type: application/json

{
    "user_id": 2
}
###
return
{
    "article_id": 1,
    "article_title": "A History of Fashion",
    "author": "Violet Lee",
    "author_pic": "http://pfpImage",
    "image_url": "http://ImageURL",
    "total_TEA_invested": 444,
    "user_stake": 22,
    "liquidation_time": 4,
    "date_posted": "12/25/2021 15:19:00"
}
###
POST http://localhost:3000/api/cash_out_command
content-type: application/json

{
    "user_id": 2,
    "article_id": 1,
    "amount": 5
}
###
return
{
    "err": //empty = success, not empty = error msg
}
###
POST http://localhost:3000/api/article_prep_page
content-type: application/json

{
    "user_id": 3
}
###
return
{
    "err": //empty = success, not empty = error msg
}
###
POST http://localhost:3000/api/article_confirmation_page
content-type: application/json

{
    "article_id": 4
}
###
return
{
    "article_title": "Top Prom Dresses picks (WEE!)",
    "liquidation_time": 3,
    "total_TEA_invested": 34
}
###
GET http://192.168.1.15:3000/